# Generated by Django 3.1.2 on 2020-11-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('name', models.CharField(max_length=254, primary_key=True, serialize=False)),
                ('total_student', models.IntegerField(max_length=20)),
            ],
        ),
    ]
