# Generated by Django 3.1.2 on 2020-11-06 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='total_student',
            field=models.IntegerField(),
        ),
    ]
