# Generated by Django 3.1.2 on 2020-11-06 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='number',
            field=models.IntegerField(),
        ),
    ]
