# Generated by Django 3.1.2 on 2020-11-16 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201106_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='semester',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.semester'),
        ),
    ]
