# Generated by Django 3.1.2 on 2020-11-16 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='code',
        ),
    ]
