# Generated by Django 3.1.2 on 2020-11-16 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_student_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='contact_no',
            field=models.CharField(max_length=20),
        ),
    ]
