# Generated by Django 3.1.2 on 2020-11-17 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20201117_1346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issued',
            old_name='due_due',
            new_name='due_date',
        ),
    ]
