# Generated by Django 3.1.2 on 2020-11-17 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20201117_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='Returned',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge', models.IntegerField(blank=True, default=0, null=True)),
                ('returned_date', models.DateTimeField(auto_now_add=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.issued')),
            ],
        ),
    ]
