# Generated by Django 3.1.2 on 2020-11-17 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_returned'),
    ]

    operations = [
        migrations.AddField(
            model_name='issued',
            name='is_returned',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
